Repository hannesa2/paho.mqtt.android, pull requests merged in 2023-07, with the labels that each got.

#475 [Reconnect crash resolve(NullPointerException)]
  serviceLibrary/src/main/java/info/mqtt/android/service/MqttConnection.kt
Labels: bug

#480 Android 14 [api34] compile issues
  basicSample/build.gradle
  build.gradle
  extendedSample/build.gradle
  serviceLibrary/build.gradle
  serviceLibrary/src/main/java/info/mqtt/android/service/ping/AlarmPingSender.kt
Labels: enhancement, WIP

#430 Energy saving [4.0]
  extendedSample/src/main/java/info/mqtt/android/extsample/internal/Connection.kt
  serviceLibrary/build.gradle
  serviceLibrary/src/main/AndroidManifest.xml
  serviceLibrary/src/main/java/info/mqtt/android/service/ping/AlarmPingSender.kt
  serviceLibrary/src/main/java/info/mqtt/android/service/ping/PingWorker.kt
Labels: enhancement, WorkMananger
